user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    proxy_cache_path /dev/shm/nginx
    levels=1:2
    keys_zone=ui_cache:5m
    max_size=200m
    inactive=24h;

    upstream api {
        server localhost:8080;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://localhost:3000;
            access_log /var/log/nginx/access_ui.log;
            error_log /var/log/nginx/error_ui.log;

            proxy_cache ui_cache;
            proxy_cache_valid 10m;

            add_header X-Cache-Status $upstream_cache_status;
        }
        location ~ ^/(api/|metrics) {
            proxy_pass http://api;
            access_log /var/log/nginx/access_api.log;
            error_log /var/log/nginx/error_api.log;
        }
    }
}
