global:
  resolve_timeout: 5m

route:
  receiver: "blackhole"

receivers:
  - name: "blackhole"

# if node-exporter is down, you won't be notified for redis being down
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    # equal: ["instance"]
